### ISSUE TITLE
imlib2 v1.7.5 broke image auto-orientation

### ISSUE THREAD

**Issue by xalexalex** [nsxiv/nsxiv-extra#6] opened 2022-01-01 18:04 UTC
Description:
After updating imlib2 from 1.7.4 to 1.7.5 (OS: Arch Linux), sxiv (and nsxiv) stopped auto-orienting JPEGs based on exif tags. I tried downgrading and the bug was fixed.

Steps to reproduce:

* download an exif-oriented JPG such as https://raw.githubusercontent.com/ianare/exif-samples/master/jpg/orientation/portrait_6.jpg
* view it with sxiv and notice it is oriented wrongly
* downgrade imlib2, repeat previous step and notice that it is now correctly oriented

**Comment by N-R-K** [comment] 2022-01-01 18:10
Duplicate of https://github.com/nsxiv/nsxiv/issues/187
Also this is the wrong repo for reporting `nsxiv` issues.

**Comment by N-R-K** [comment] 2022-01-01 18:13
As of now, you can either apply https://github.com/nsxiv/nsxiv/pull/188 if you're building from source or if you're using binary packages then you'll need to stick with `imlib2 1.7.4` until we release next `nsxiv` version.

**Closed by N-R-K** 2022-01-01 18:13 UTC
